profile: dev_envrimont

project:
  runmode: singleton
  singleton:
    enterprise:
  root-path:
  deploy:
    mode: normal

server:
  port: 8088
  servlet:
    domain-path: http://180.153.238.189:8189
    context-path:
    session:
      timeout:

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location:
      max-file-size: 100MB
      max-request-size: 100MB
      resolve-lazily: false

datasource:
  monitor:
    username: druid
    password: WyED1U5tAGgvlAiRHHcfCql1TFcN6s2ZzJDYkoYtiwJmwiihBjgwLh+SXurd5xIyWh7i47Orr47aOWcC04R4Fw==
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJVxkAgbxBEyDno6bEZY8nOlQWeDtSnr4TZaSSARB/Eh7/CrE/fXUME/qlaqT9CMTLlICootoVrkGOGENoyVJBMCAwEAAQ==
  tocer:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://222.73.22.141:3306/minhang?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: NHJKQtx1Or5Xh3i0wB07zDz2TmzvlUfO9fJSdyQ0zwmNWlNzIFdKFwnYoHeVA89SvLhmiYhCo9bPWHURTe+HaA==
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAM9/Qhs5UNxe/LgVm+cEvrEgqonGHslj0RUNzYzsHXy0Jl+YNQP4o+eJMzMdwZel5pbiItNYaGZm3IQJehwB7EECAwEAAQ==
    initialSize: 2
    minIdle: 2
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

logging:
  config: classpath:log-dev.xml